### ISSUE TITLE
貌似Lock失效了，会异常

### ISSUE THREAD

**Issue by Yodamt** [TheWanderingCoel/BiliBiliHelper#1]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Anaconda3\envs\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:/BiliBiliHelper-master/BiliBiliHelper-master/main.py", line 67, in daily_job
    Coin2Silver.work()
  File "Src\Coin2Silver.py", line 23, in work
    if self.lock > int(time.time()):
AttributeError: 'Coin2Silver' object has no attribute 'lock'

**Comment by TheWanderingCoel** [comment]
写的粗心了,在Coin2Silver.py中把def __init__(self)写成了def __init(self)    
现在已修复并进行了测试,感谢支持呀

**Comment by Yodamt** [comment]
> 写的粗心了,在`Coin2Silver.py`中把`def __init__(self)`写成了`def __init(self)`
> 现在已修复并进行了测试,感谢支持呀

还有main.py 
from Raffle_Handler import RaffleHandler
前面导入写成了raffle_handler 会导致导入失败

**Comment by TheWanderingCoel** [comment]
> > 写的粗心了,在`Coin2Silver.py`中把`def __init__(self)`写成了`def __init(self)`
> > 现在已修复并进行了测试,感谢支持呀
> 
> 还有main.py
> from Raffle_Handler import RaffleHandler
> 前面导入写成了raffle_handler 会导致导入失败

是的,原来名字是raffle_handler.py后来改成了Raffle_Handler.py没注意,感谢。
