### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by 2438175594** [TheWanderingCoel/BiliBiliHelper#9]
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    from Monitor_Server import MonitorServer
  File "/data/data/com.termux/files/home/BiliBiliHelper/Src/Monitor_Server.py", line 23, in <module>
    from Anchor_Raffle_Handler import AnchorRaffleHandler
  File "/data/data/com.termux/files/home/BiliBiliHelper/Src/Anchor_Raffle_Handler.py", line 5, in <module>
    if platform.system() == "Windows":
NameError: name 'platform' is not defined
![Screenshot_2020-01-30-16-38-35-85](https://user-images.githubusercontent.com/46627115/73433252-630e2380-437f-11ea-81f6-df18e4441b75.png)

**Comment by TheWanderingCoel** [comment]
我觉得我应该创建一个dev分支进行开发，然后合并。先``git checkout 21f29790382e326db3806580e275d184c14aacb8``吧
